version: "3.8"


services:
  caddy:
    image: caddy:2.7-alpine
    container_name: caddy
    ports:
      - "8085:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - geth
    networks:
      - geth-network
  sc-deployer:
    image: ghcr.io/foundry-rs/foundry:latest
    platform: linux/arm64
    container_name: sc-deployer
    user: root
    volumes:
      - ./sc-deployer:/workspace
      - ./geth-init:/shared
    working_dir: /workspace
    entrypoint: ["/bin/sh", "/workspace/entrypoint.sh"]
    depends_on:
      - geth
    networks:
      - geth-network
  sc-deployment-server:
    image: caddy:2.7-alpine
    container_name: sc-deployment-server
    ports:
      - "8081:80"
    volumes:
      - ./sc-deployment-server/Caddyfile:/etc/caddy/Caddyfile
      # serve deployment.json
      - ./sc-deployer:/usr/share/caddy
    depends_on:
      - sc-deployer
    networks:
      - geth-network
  geth:
    image: ethereum/client-go:v1.15.0
    container_name: geth
    ports:  
      - "8545:8545"
      - "8546:8546"  # Add WebSocket port
      - "30303:30303"  # P2P
      - "30303:30303/udp"  # P2P UDP
    volumes:
      - geth-data:/root/.ethereum
      - ./geth:/geth
    command: >
      --dev
      --datadir /root/.ethereum
      --http
      --http.addr 0.0.0.0
      --http.port 8545
      --http.corsdomain "*"
      --http.vhosts "*"
      --http.api "eth,net,web3,personal,miner,admin,debug,txpool"
      --ws
      --ws.addr 0.0.0.0
      --ws.port 8546
      --ws.api "eth,net,web3,personal,miner,admin,debug,txpool"
      --ws.origins "*"
      --allow-insecure-unlock
      --mine
      --networkid 1337
      --nodiscover
      --verbosity 3
      --miner.gaslimit 8000000
    restart: unless-stopped
    networks:
      - geth-network
  geth-init:
    image: ethereum/client-go:v1.15.0
    container_name: geth-init
    volumes:
      - ./geth-init:/scripts
      - geth-data:/root/.ethereum
      - ./geth-init:/shared
    entrypoint: ["/bin/sh", "/scripts/entrypoint.sh"]
    depends_on:
      - geth
    networks:
      - geth-network
  graph-postgres:
    image: postgres:13
    container_name: graph-postgres
    environment:
      POSTGRES_USER: graph
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    command: postgres -c 'max_connections=100' -c 'shared_buffers=256MB' -c 'log_statement=all' -c 'log_connections=on' -c 'log_disconnections=on'
    volumes:
      - graph-postgres-data:/var/lib/postgresql/data
    networks:
      - geth-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U graph"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  graph-ipfs:
    image: ipfs/kubo:v0.22.0
    container_name: graph-ipfs
    networks:
      - geth-network
  graph-redis:
    image: redis:7.0.12
    container_name: graph-redis
    ports:
      - "6379:6379"
    networks:
      - geth-network
  graph-node:
    image: graphprotocol/graph-node:v0.33.0
    container_name: graph-node
    depends_on:
      graph-postgres:
        condition: service_healthy
      graph-ipfs:
        condition: service_started
    environment:
      postgres_host: graph-postgres
      postgres_user: graph
      postgres_pass: let-me-in
      postgres_db: graph
      ipfs: "graph-ipfs:5001"
      ethereum: "mainnet:http://geth:8545"
      GRAPH_LOG: debug
      RUST_BACKTRACE: 1
    networks:
      - geth-network
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8020:8020"
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    container_name: graph-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8083:80"
    networks:
      - geth-network
    depends_on:
      - graph-node
      - geth
    restart: always


volumes:
  geth-data:
  graph-postgres-data:


networks:
  geth-network:
    name: 1b_geth-network
    external: true